kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "quarkus-rest.fullname" . }}
  labels:
    {{- include "quarkus-rest.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replica_count }}
  template:
    metadata:
      labels:
        {{- include "quarkus-rest.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "quarkus-rest.fullname" . }}
          image: "{{ .Values.image_registry }}/{{ .Values.image_namespace}}/{{ .Values.image_name }}@{{ .Values.image_digest }}"
          ports:
            - containerPort: 8080
              protocol: TCP
              name: 8080-tcp
            - containerPort: 8443
              protocol: TCP
              name: 8443-tcp
