apiVersion: v1
kind: Service
metadata:
  name: {{ include "quarkus-rest.fullname" . }}
  labels:
    {{- include "quarkus-rest.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: 8080-tcp
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: 8443-tcp      
  selector:
    {{- include "quarkus-rest.selectorLabels" . | nindent 4 }}
